/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.27
 * Generated at: 2024-12-15 09:24:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import Model.BEAN.User;

public final class Index_005fbooking_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("Model.BEAN.User");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"vi\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Quản Lý Booking</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        body {\r\n");
      out.write("           font-family: Arial, sans-serif;\r\n");
      out.write("	        margin: 0;\r\n");
      out.write("	        padding: 0;\r\n");
      out.write("        }\r\n");
      out.write("        .header {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            margin-bottom: 30px;\r\n");
      out.write("        }\r\n");
      out.write("        .header h1 {\r\n");
      out.write("            font-size: 28px;\r\n");
      out.write("            color: #333;\r\n");
      out.write("        }\r\n");
      out.write("        .button-container {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            margin-bottom: 20px;\r\n");
      out.write("        }\r\n");
      out.write("        .button {\r\n");
      out.write("            background-color: #4CAF50;\r\n");
      out.write("            color: white;\r\n");
      out.write("            padding: 10px 20px;\r\n");
      out.write("            margin: 10px;\r\n");
      out.write("            font-size: 16px;\r\n");
      out.write("            border: none;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("        }\r\n");
      out.write("        .button:hover {\r\n");
      out.write("            background-color: #45a049;\r\n");
      out.write("        }\r\n");
      out.write("        h1{\r\n");
      out.write("    	text-align: center;\r\n");
      out.write("    }\r\n");
      out.write("    .navbar {\r\n");
      out.write("        background-color: #007BFF; /* Màu xanh chủ đạo */\r\n");
      out.write("        overflow: hidden;\r\n");
      out.write("        display: flex;\r\n");
      out.write("        justify-content: space-between;\r\n");
      out.write("        padding: 10px 20px;\r\n");
      out.write("    }\r\n");
      out.write("    .navbar a {\r\n");
      out.write("        color: white;\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("        padding: 8px 16px;\r\n");
      out.write("        font-size: 16px;\r\n");
      out.write("    }\r\n");
      out.write("    .navbar a:hover {\r\n");
      out.write("        background-color: #0056b3; /* Màu xanh đậm hơn khi hover */\r\n");
      out.write("        border-radius: 4px;\r\n");
      out.write("    }\r\n");
      out.write("    .links {\r\n");
      out.write("        display: flex;\r\n");
      out.write("        gap: 20px;\r\n");
      out.write("    }\r\n");
      out.write("    .content {\r\n");
      out.write("        margin: 20px;\r\n");
      out.write("    }\r\n");
      out.write("    .content a {\r\n");
      out.write("        display: inline-block;\r\n");
      out.write("        background-color: #007BFF; /* Màu nền xanh chủ đạo */\r\n");
      out.write("        color: white;\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("        padding: 10px 20px;\r\n");
      out.write("        border-radius: 5px;\r\n");
      out.write("        margin: 5px 0;\r\n");
      out.write("        font-size: 18px;\r\n");
      out.write("    }\r\n");
      out.write("    .content a:hover {\r\n");
      out.write("        background-color: #0056b3; /* Màu nền xanh đậm hơn khi hover */\r\n");
      out.write("    }\r\n");
      out.write("    .btn-logout {\r\n");
      out.write("        background-color: #007BFF; /* Màu nền xanh chủ đạo */\r\n");
      out.write("        color: white; /* Màu chữ */\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("        padding: 10px 20px; /* Khoảng cách bên trong */\r\n");
      out.write("        border: none; /* Bỏ viền */\r\n");
      out.write("        border-radius: 5px; /* Bo góc */\r\n");
      out.write("        font-size: 18px; /* Kích thước chữ */\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .btn-logout:hover {\r\n");
      out.write("        background-color: #0056b3; \r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .btn-logout:focus {\r\n");
      out.write("        outline: none; /* Bỏ viền focus mặc định */\r\n");
      out.write("    }\r\n");
      out.write("    .group-btn{\r\n");
      out.write("    	margin-top:10px;\r\n");
      out.write("    }\r\n");
      out.write("    .welcome-user{\r\n");
      out.write("    	display: flex;\r\n");
      out.write("    	gap:20px;\r\n");
      out.write("    }\r\n");
      out.write("    .welcome-user span{\r\n");
      out.write("	color: white;\r\n");
      out.write("	margin-top:7px;\r\n");
      out.write("	font-size: 20px;\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");

        	User user = (User) session.getAttribute("user");
        	if(user == null || user.getRole() == null){
        
      out.write("\r\n");
      out.write("      <div class=\"navbar\">\r\n");
      out.write("       <div class=\"links\">\r\n");
      out.write("           <a href=\"WelcomeUser.jsp\">Home Page</a>\r\n");
      out.write("           <a href=\"WelcomeAdmin.jsp\">Admin Page</a>\r\n");
      out.write("       </div>\r\n");
      out.write("        <div class=\"group-btn\">\r\n");
      out.write("            <a href=\"Login.jsp\">Đăng nhập</a>\r\n");
      out.write("            <a href=\"Register.jsp\">Đăng ký</a>\r\n");
      out.write("        </div>\r\n");
      out.write("     </div>\r\n");
      out.write("     <div class=\"content\">\r\n");
      out.write("       	<h1>Bạn cần đăng nhập để thực hiện chức năng này</h1>\r\n");
      out.write("   	</div>\r\n");
      out.write("        ");
 }
        	else{
        
      out.write("\r\n");
      out.write("        <div class=\"navbar\">\r\n");
      out.write("	       <div class=\"links\">\r\n");
      out.write("	           <a href=\"WelcomeUser.jsp\">Home Page</a>\r\n");
      out.write("	           <a href=\"WelcomeAdmin.jsp\">Admin Page</a>\r\n");
      out.write("	       </div>\r\n");
      out.write("	        <form action=\"AuthController\" method=\"post\">\r\n");
      out.write("	        	<div class=\"welcome-user\">\r\n");
      out.write("	        		<span>Xin chào, ");
      out.print(user.getFullName() );
      out.write("</span>\r\n");
      out.write("	            	<button class=\"btn-logout\" type=\"submit\">Đăng xuất</button>\r\n");
      out.write("	            	<input  type=\"hidden\" value=\"logout\" name=\"action\">\r\n");
      out.write("	        	</div>\r\n");
      out.write("	        </form>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"header\">\r\n");
      out.write("        <h1>Quản Lý Booking</h1>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"button-container\">\r\n");
      out.write("        <!-- Nút Create Booking -->\r\n");
      out.write("        <a href=\"BookingController?action=create\" class=\"button\">Create Booking</a>\r\n");
      out.write("        <!-- Nút View Booking -->\r\n");
      out.write("        <a href=\"BookingController?action=view\" class=\"button\">View Booking</a>\r\n");
      out.write("        <!-- Nút Search Booking -->\r\n");
      out.write("        <a href=\"BookingController?action=search\" class=\"button\">Search Booking</a>\r\n");
      out.write("        <!-- Nút Delete Booking -->\r\n");
      out.write("        <a href=\"BookingController?action=delete\" class=\"button\">Delete Booking</a>\r\n");
      out.write("        <!-- Nút Update Booking -->\r\n");
      out.write("        <a href=\"BookingController?action=update\" class=\"button\">Update Booking</a>\r\n");
      out.write("        <!-- Nút Quay Lại -->\r\n");
      out.write("        <a href=\"WelcomeAdmin.jsp\" class=\"button\" style=\"background-color: #007BFF;\">Return</a>\r\n");
      out.write("    </div>\r\n");
      out.write("        ");

        	}
        
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
